spring:
  application:
    name: hex4j-webflux-template
  
  profiles:
    active: dev
  
  # R2DBC H2 Database configuration
  r2dbc:
    url: r2dbc:h2:mem:///hex4jwebflux;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  
  # SQL initialization
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
    
  # H2 Console configuration (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: 8080

# Application-specific configuration
app:
  webclient:
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 10000
    max-memory-size: 1048576
  notification:
    base-url: http://localhost:8081

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Logging configuration
logging:
  level:
    root: INFO
    co.onmind.hex4jwebflux: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG
    org.springframework.web.reactive: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev
      
logging:
  level:
    co.onmind.hex4jwebflux: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
      
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    
logging:
  level:
    root: WARN
    co.onmind.hex4jwebflux: INFO

---
spring:
  config:
    activate:
      on-profile: prod
      
logging:
  level:
    root: WARN
    co.onmind.hex4jwebflux: INFO